functional:
  - На сайте должна быть реализована функция авторизации
  - Сайт должен запоминать и фиксировать данные о пользователях
  - Необходима функция восстановления пароля пользователя
  - Для пользователей должен быть разработан внутренний чат
  - Пользователям сайта должна быть предоставлена возможность изменения данных в своих профилях
  - Зарегистрированные пользователи должны иметь возможность установки и иизменения в своём профиле аватара
  - На сайте должна быть реализована функция "начать игру"
  - Необходима реализация нескольких режимов игры "игрок против игрока" / "игрок против компьютера"
  - Во время состязания должен быть реализован чат между игроками
  - В игре должна быть функция проверки правильности решения задачи
  - У пользователей во время состязания не должно быть возможности корректирования кода соперника
  - У пользователей во время состязания не должно быть возможности копирования кода соперника
  - Должно быть реализовано завершение игры с несколькими сценариями
  - У пользователя должна быть возможность удаления своей учётной записи
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен поддерживать мультиязычность 
implicit:
  - На сайт должны быть добавлены задачи разного уровня сложности
  - Игра должна поддерживать все основные языки программирования